# .github/workflows/load-data-reusable.yml
name: Load data into Salesforce

on:
  workflow_call:
    inputs:
      config-file:
        required: true
        type: string

jobs:
  sfdmu:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      SFDMU_CLIENT_ID:     ${{ env.SFDMU_CLIENT_ID }}
      SFDMU_CLIENT_SECRET: ${{ env.SFDMU_CLIENT_SECRET }}
      SFDMU_USERNAME:      ${{ env.SFDMU_USERNAME }}
      SFDMU_PASSWORD:      ${{ env.SFDMU_PASSWORD }}
      SF_SECURITY_TOKEN:   ${{ env.SF_SECURITY_TOKEN }}
      SFDMU_INSTANCE_URL:  ${{ env.SFDMU_INSTANCE_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Salesforce CLI
        run: npm install --global @salesforce/cli

      - name: Install SFDMU plugin
        run: sf plugins install sfdmu

      - name: Authenticate via Username-Password grant
        run: |
          sf auth:password:grant \
            --client-id     "$SFDMU_CLIENT_ID" \
            --client-secret "$SFDMU_CLIENT_SECRET" \
            --username      "$SFDMU_USERNAME" \
            --password      "${SFDMU_PASSWORD}${SF_SECURITY_TOKEN}" \
            --instance-url  "$SFDMU_INSTANCE_URL"

      - name: Run SFDMU data load
        run: |
          sf sfdmu run \
            --configfile "${{ inputs.config-file }}"
