name: Load data into Salesforce
on:
  workflow_call:
    inputs:
      config-file:
        required: true
        type: string

jobs:
  sfdmu:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      SFDMU_USERNAME:     ${{ secrets.SFDMU_USERNAME }}
      SFDMU_CLIENT_ID:    ${{ secrets.SFDMU_CLIENT_ID }}
      SFDMU_JWT_KEY:      ${{ secrets.SFDMU_JWT_KEY }}
      SFDMU_INSTANCE_URL: ${{ secrets.SFDMU_INSTANCE_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Salesforce CLI
        run: |
          npm install --global @salesforce/cli
          

      - name: Install SFDMU 
        run: |
         sf plugins install sfdmu


