name: Salesforce Data Loader

on:
  push:
    paths:
      - 'data/**'
      - 'config/**'
      - '.github/workflows/sfdmu-load.yml'

concurrency:
  group: sfdmu-load-${{ github.ref }}
  cancel-in-progress: true

jobs:
  load:
    # Call the reusable workflow
    uses: ./.github/workflows/load-data-reusable.yml
    with:
      config-file: config/upsert-accounts.yml
