name: Salesforce Data Loader

on:
  push:
    paths:
      - 'data/**'
      - 'config/**'
      - 'scripts/**'
      - '.github/workflows/sfdmu-load.yml'

concurrency:
  group: sfdmu-load-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    runs-on: ubuntu-latest
    outputs:
      valid: ${{ steps.check.outputs.passed }}
    steps:
      - uses: actions/checkout@v4
      - name: Validate CSV Schema
        id: check
        run: |
          bash scripts/validate-csv.sh
          echo "::set-output name=passed::true"

  load:
    needs: validate
    if: needs.validate.outputs.valid == 'true'
    uses: ./.github/workflows/reusable/load-data.yml
    with:
      config-file: config/upsert-accounts.yml
    environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'development' }}
