# .github/workflows/sfdmu-load.yml
name: Salesforce Data Loader (Username-Password)

on:
  push:
    paths:
      - 'data/**'
      - 'config/**'
      - '.github/workflows/sfdmu-load.yml'

concurrency:
  group: sfdmu-load-${{ github.ref }}
  cancel-in-progress: true

jobs:
  load:
    uses: ./.github/workflows/load-data-reusable.yml
    with:
      config-file: config/upsert-accounts.yml
      env:
      SFDMU_CLIENT_ID:     ${{ secrets.SFDMU_CLIENT_ID }}
      SFDMU_CLIENT_SECRET: ${{ secrets.SFDMU_CLIENT_SECRET }}
      SFDMU_USERNAME:      ${{ secrets.SFDMU_USERNAME }}
      SFDMU_PASSWORD:      ${{ secrets.SFDMU_PASSWORD }}
      SF_SECURITY_TOKEN:   ${{ secrets.SF_SECURITY_TOKEN }}
      SFDMU_INSTANCE_URL:  https://login.salesforce.com

  verify-login:
    needs: load
    runs-on: ubuntu-latest
    env:
      SFDMU_CLIENT_ID:     ${{ secrets.SFDMU_CLIENT_ID }}
      SFDMU_CLIENT_SECRET: ${{ secrets.SFDMU_CLIENT_SECRET }}
      SFDMU_USERNAME:      ${{ secrets.SFDMU_USERNAME }}
      SFDMU_PASSWORD:      ${{ secrets.SFDMU_PASSWORD }}
      SF_SECURITY_TOKEN:   ${{ secrets.SF_SECURITY_TOKEN }}
      SFDMU_INSTANCE_URL:  https://login.salesforce.com

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Salesforce CLI
        run: npm install --global @salesforce/cli

      - name: Install SFDMU plugin
        run: sf plugins install sfdmu

      - name: Authenticate via Username-Password grant
        run: |
          sf auth:password:grant \
            --client-id     "$SFDMU_CLIENT_ID" \
            --client-secret "$SFDMU_CLIENT_SECRET" \
            --username      "$SFDMU_USERNAME" \
            --password      "${SFDMU_PASSWORD}${SF_SECURITY_TOKEN}" \
            --instance-url  "$SFDMU_INSTANCE_URL"

      - name: Verify org login
        run: sf org display --targetusername "$SFDMU_USERNAME"
